project:
  type: book

book:
  repo-url: https://github.com/smart-stats/ds4bio_book
  title: "Data science and AI for the biological and medical sciences using python"
  author: "Brian Caffo"
  date: "2/24/2023"
  sidebar:
    title: "DS&AI4B&MSUP"
    logo: assets/images/dasl.png   
    collapse-level: 1
    
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - intro_markdown.qmd
#        - intro_unix.qmd
#        - intro_git.qmd
#        - intro_html.qmd
#    - part: python.qmd
#      chapters:
#        - python_basic.qmd
#        - python_programming.qmd
#        - python_functions.qmd
#        - python_virtual_environments.qmd
#        - python_practice.qmd
#    - part: data.qmd
#      chapters:
#        - data_cleaning_example.qmd
#        - data_sqlite.qmd
#        - data_advanced_databases.qmd
#        - data_webscraping.qmd
#        - data_advanced_webscraping.qmd
#    - part: graphics.qmd
#      chapters:
#        - graphics_eda.qmd
#        - graphics_interactive.qmd
#        - graphics_advanced_interactive.qmd
#        - graphics_theory.qmd
#        - graphics_images.qmd
#    - part: tooling.qmd
#      chapters:
#        - tooling_nlp.qmd
#        - tooling_numpy.qmd
#        - tooling_streamlit.qmd
#        - tooling_dash.qmd
#    - part: statistics.qmd
#      chapters:
#         - statistics_ml.qmd
#         - statistics_optimization.qmd
#         - statistics_causal.qmd
#    - part: supervised.qmd
#      chapters:
#          - supervised_binary_classification.qmd
#          - supervised_regression_origin.qmd
#          - supervised_regression.qmd
#          - supervised_logistic.qmd
#          - supervised_multivariable.qmd
#          - supervised_dft.qmd
#    - part: unsupervised.qmd
#      chapters:
#        - unsupervised_pca_ica.qmd
#    - part: nns.qmd 
#      chapters:
#           - nns_intro.qmd
#           - nns_basic_regression.qmd
#           - nns_logistic_regression.qmd
#           - nns_pytorch_example.qmd
#    - part: specialized.qmd
#      chapters:
#           - specialized_autoencoder.qmd
#           - specialized_autoencoder2.qmd
#           - specialized_gan.qmd
#           - specialized_rnns.qmd
#           - specialized_gpu.qmd 
#    - part: theory.qmd
#      chapters:
#          - theory_explainability.qmd
#          - theory_data_analysis.qmd
#          - theory_measurement.qmd
    - part: summary.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



